config/routes.rb
Rails.application.routes.draw do
  get 'staffs/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, only: [:index]
  resources :staffs, only: [:index]
  resources :languages, except: [:show]
  resources :demonstrations, only: [:index] do
    collection do
      post :index
      get :export_staffs
    end
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :staffs

  validates :name, presence: true, uniqueness: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :language

  validates :name, presence: true
  validates :language_id, presence: true

  before_validation :set_default_language, if: Proc.new { |staff| staff.language_id.nil? }

  def set_default_language
    assign_attributes(language_id: Language.first.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demonstrations_controller.rb
class DemonstrationsController < ApplicationController
  def index
    binding.pry
    @staffs = Staff.includes(:language)
                   .all
                   .page(params[:page])
                   .per(10)
    @long_param = params[:long_parameter]
  end

  def export_staffs
    xlsx_file_name = 'samples.xlsx'
    response.headers['Content-Disposition'] = 'attachment;'
    render xlsx: 'staff_list', filaname: xlsx_file_name, locals: { staffs: Staff.includes(:language).all }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def create
    binding.pry
    redirect_to demonstrations_path, notice: 'hoge'
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: StaffDatatable.new(params) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demonstrations_helper.rb
module DemonstrationsHelper
end

app/views/demonstrations/index.html.haml
= link_to 'export_staffs', export_staffs_demonstrations_path(format: :xlsx)

= form_with(model: Language.new) do |f|
  = f.text_field :name
  = f.submit 'hoge'

%h2 kaminari sample

= form_with(url: demonstrations_path, method: :post, local: true) do |f|
  = text_field_tag :long_parameter, 'あああああいいいいい'
  = f.submit 'OK'

%table
  %tr
    %th ID
    %th Language
    %th Name
  - @staffs.each do |staff|
    %tr
      %td= staff.id
      %td= staff.language.name
      %td= staff.name

= paginate @staffs, params: { long_parameter: @long_param }

app/views/home/index.html.haml
%h1 Home#index

= link_to 'demonstrations', demonstrations_path

%table#staffs-datatable{ 'data-source': staffs_path(format: :json) }
  %thead
    %tr
      %th ID
      %th Name
  %tbody

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Laboratory
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield